version: "3.1"

services:

  db:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=t3kit
      - MYSQL_USER=t3kit
      - MYSQL_PASSWORD=t3kit1234
    restart: always

  web:
    container_name: web
    image: t3kit/ubuntu16-php7-apache:0.0.1
    ports:
      - "8888:80"
    depends_on:
      - db
    volumes:
      - ./docker_conf:/docker_conf
      - ./vendor/t3kit/db:/t3kit_db
      - .:/var/www/html
    restart: always
    command: "sh /docker_conf/run.sh"
