<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'ApacheSolrForTypo3\\Solr\\' => array($typo3InstallDir . 'typo3conf/ext/solr/Classes'),
    'ApacheSolrForTypo3\\Solr\\Tests\\' => array($typo3InstallDir . 'typo3conf/ext/solr/Tests'),
    'B13\\SeoBasics\\' => array($typo3InstallDir . 'typo3conf/ext/seo_basics/Classes'),
    'Clickstorm\\GoMapsExt\\' => array($typo3InstallDir . 'typo3conf/ext/go_maps_ext/Classes'),
    'DmitryDulepov\\Realurl\\' => array($typo3InstallDir . 'typo3conf/ext/realurl/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'KayStrobach\\Dyncss\\' => array($typo3InstallDir . 'typo3conf/ext/dyncss/Classes'),
    'KayStrobach\\Themes\\' => array($typo3InstallDir . 'typo3conf/ext/themes/Classes'),
    'SJBR\\StaticInfoTables\\' => array($typo3InstallDir . 'typo3conf/ext/static_info_tables/Classes'),
    'T3kit\\T3kitExtensionTools\\' => array($typo3InstallDir . 'typo3conf/ext/t3kit_extension_tools/Classes'),
    'T3kit\\themeT3kit\\' => array($typo3InstallDir . 'typo3conf/ext/theme_t3kit/Classes'),
);
